common/urls.py
app_name='common'

from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('photo-add/', admin.site.urls),
    path('common/', include('common.urls')),
    path('', include('cook.urls')),
]

cook/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import PhotoListView, PhotoDetailView, Random

urlpatterns = [
    path("photo/<int:pk>", PhotoDetailView.as_view(), name="photo-detail"),
    path("random", Random, name='random'),
    path('', PhotoListView.as_view(), name='photo-list'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.

cook/models.py
from django.db import models

class Tag(models.Model):
    name = models.CharField(max_length=32, primary_key=True)

    def __str__(self):
        return self.name

class Photo(models.Model):
    image = models.ImageField(null=False, blank=False, upload_to="uploads/")
    name = models.CharField(max_length=20, null=False, blank=False)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name

common/views.py
from django.shortcuts import render

# Create your views here.

cook/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Photo
import random

class PhotoListView(ListView):
    model = Photo
    ordering = ['-created_at']
    template_name = "photo_list.html"
    context_object_name = "photos"

class PhotoDetailView(DetailView):
    model = Photo
    template_name = "photo_detail.html"
    context_object_name = "photo"

def Random(req):
    print(req.user)
    context = random.choice(Photo.objects.all())
    return render(req, 'random.html',{'photo':context})

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="jp">
<html>
	<head>
		<!-- META Data -->
		<meta charset="UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		
		<!-- CSS Data -->
		<link rel='stylesheet' href='{% static "css/reset.css" %}' />
		<link 
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
			rel="stylesheet" 
			integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
			crossorigin="anonymous"
		/>
		<link rel='stylesheet' href='{% static "css/main.css" %}' />
	</head>
	<body>
		<!-- GNB Area -->
		{% block global_menu %}
		{% endblock global_menu %}
		
		<!-- Contents Area -->
		{% block bodys %}
		{% endblock bodys %}
	</body>
</html>

templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
	{% for field in form %}
		<!-- 필드 오류 -->
		{% if field.errors %}
		<div>
			<strong>{{ field.label }}</strong>
			{{ field.errors }}
		</div>
		{% endif %}
	{% endfor %}
	<!-- 넌필드 오류 -->
	{% for error in form.non_field_errors %}
	<div>
		<strong>{{ error }}</strong>
	</div>
	{% endfor %}
</div>
{% endif %}

templates/global_menu.html
{% extends 'base.html' %}

{% block global_menu %}
		<nav>
			<h1 class='title'>李と林の<br>メニューリスト</h1>
			<ul class='menu'>
				<li><a href="{% url 'photo-list' %}">Home</a></li>
				<li><a href="{% url 'photo-list' %}">Menu list</a></li>
				{% if user.is_authenticated %}
				<li><a href="photo-add/">Add menu</a></li>
				{% else %}
				<li><a href="{% url 'common:login' %}">Add menu</a></li>
				{% endif %}
				<li><a href="{% url 'random' %}">Menu game</a></li>
				{% if user.is_authenticated %}
				<li><a href="{% url 'common:logout' %}">Logout</a></li>
				{% endif %}
			</ul>
			<div class="align-self-end">
			</div>
		</nav>
{% endblock global_menu %}

{% block bodys %}
		<div class="section">
			{% block body %}
			{% endblock body %}
		</div>
{% endblock bodys %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>今日のメニューリスト</title>
<link rel='stylesheet' href='{% static "css/main.css" %}' />
{% endblock %}

{% block body %}
<div class='section'>
	<div class='container'>
		{% for photo in photos %}
		<div class='deck'>
			<div class="card" style="background-image:url(http://menuplanner.li-lim.com{{ photo.image.url }});"></div>
			<div class="card-body">
				<p class="card-name">
					{{photo.name}}
				</p>
				<p class="card-tag">
					{% for tag in photo.tags.all %}
					#{{tag}}
					{% endfor %}
				</p>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}

templates/login.html
{% extends "global_menu.html" %}
{% block body %}
<div class="container my-3">
	{% include "user.html" %}
	<form method="post" action="{% url 'common:login' %}">
	{% csrf_token %}
	<div class="mb-3 d-flex">
		<div class="me-3 col-2"><label for="username">ID</label></div>
		<input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
	</div>
	<div class="mb-3 d-flex">
		<div class="me-3 col-2"><label for="password">Password</label></div>
		<input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
	</div>
	{% include "form_errors.html" %}
	<div class="container d-flex justify-content-center">
		<button type="submit" class="btn btn-primary">Login</button>
	</div>
	</form>
</div>
{% endblock %}

templates/photo_detail.html
{% extends 'global_menu.html' %}

{% block body %}
<div class="container">
	<img src="{{ photo.image.url }}" height="600px" />
	<p>{{ photo.created_at }}</p>
	<h4>{{ photo.name }}</h4>
	<p>
		{% for tag in photo.tags.all %}
		#{{ tag }}
		{% endfor %}
	</p>
	<hr/>
	<p>{{ photo.description|linebreaksbr }}</p>
</div>
{% endblock body %}

templates/photo_list.html
{% extends 'global_menu.html' %}

{% block body %}
			<div class="container">
				<div class="row">
					{% for photo in photos %}
					<div class="col-12 col-md-4">
						<div class="card">
							<a href="{% url 'photo-detail' photo.pk  %}">
								<img src="{{ photo.image.url }}" width="400px" height="400px" class="card-img-top"/>
								<div class="card-body">
									<p class="card-text">
										<h5>{{ photo.name }}</h5>
										{% for tag in photo.tags.all %}
										#{{ tag }}
										{% endfor %}
									</p>
								</div>
							</a>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
{% endblock body %}

templates/random.html
{% extends 'global_menu.html' %}
{% block body %}
<div class="container random">
	<img src="{{ photo.image.url }}" height="600px" />
	<p>{{ photo.created_at }}</p>
	<h4>{{ photo.name }}</h4>
	<p>
		{% for tag in photo.tags.all %}
		#{{ tag }}
		{% endfor %}
	</p>
	<hr/>
	<p>{{ photo.description|linebreaksbr }}</p>
</div>
{% endblock body %}

templates/user.html
<div class="row mb-3">
	{% if user.is_authenticated %}
	<button class="btn btn-outline-secondary">{{ user.name }}</button>
	{% endif %}
</div>